name: bpl
channels:
  - conda-forge
  - defaults
dependencies:
  - antlr=4.7.2=2
  - conda=4.7.10=py37_0
  - matplotlib=3.1.0=py37h5429711_0
  # install npm (necessary to install various dependencies, see below)
  - nodejs=10.13.0=he6710b0_0
  - nose=1.3.7=py37_2
  - pandas=0.25.0=py37he6710b0_0
  - parameterized=0.7.0=py37_0
  - pip=19.0.3=py37_0
  - python=3.7.3=h0371630_0
  - pip:
    - antlr4-python3-runtime==4.7.2
    - py-solc==3.2.0